name: CI

on: [push, pull_request]

jobs:
  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Run bandit
        run: nox -s bandit

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Run doc
        run: nox -s doc

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Run flake8
        run: nox -s flake8

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Run pylint
        run: nox -s pylint

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install nox

      - name: Run pytest
        run: nox -s pytest
        env:
          INSIGHT_API_KEY: ${{ secrets.INSIGHT_API_KEY }}
